### ISSUE TITLE
Build folder quite big

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#18]
just curious to understand why the build folder is so big

**Comment by CodeCombiner** [comment]
After quick look I can see that some part is taken by native libraries and files in tealeaf module and the biggest part is taken by build/intermediates/transforms directory which stores intermediate dex files before shrinking them

**Comment by rampr** [comment]
1. The build folder sizes are split like this. The `tealeaf` folder I think is a copy of the source code which doesn't need to be present in the build folder.
> 531M	app
> 7.1M	build
> 4.0K	build.gradle
> 60K	gradle
> 4.0K	gradle.properties
> 8.0K	gradlew
> 4.0K	gradlew.bat
> 4.0K	proguard-rules.pro
> 4.0K	settings.gradle
> 241M	tealeaf

2. Also, I took a closer look at each of the folders in the build folder.
The other issue I see is that both debug and release are created when building. Please check screenshot below
<img width="606" alt="screen shot 2018-07-03 at 11 52 01 am" src="https://user-images.githubusercontent.com/100719/42201991-9fd63cdc-7eb7-11e8-8c6b-3ffd37df2d7e.png">

When running `devkit debug native-android` only the debug apk/intermediaries are sufficient
When running `devkit release native-android` only the release apk/intermediaries are sufficient

3. The build folder is already separated into cache, debug and release and based on what is being built, the corresponding build folder is created. Right now a separate sqmtest folder is created that has both debug and release. I would like the old system to be maintained. So if `devkit debug` is being run then the `debug` folder has everything that is needed and similary for the `release` folder

Please let me know your thoughts

**Comment by CodeCombiner** [comment]
It is related to plugins dependencies. native-android game project with full plugins list uses near 100  dependencies and subdependencies.

**Comment by rampr** [comment]
Can this be closed ?

**Comment by CodeCombiner** [comment]
Yes
