### ISSUE TITLE
Error in flurry

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#22]
I'm not sure if this is serious. But noting it down just in case

07-02 15:17:06.730 4855-4877/com.hashcube.sqmtest D/FlurryAgent: Referrer file contents: null
07-02 15:17:06.735 4855-4875/com.hashcube.sqmtest I/FA: Tag Manager is not found and thus will not be used
07-02 15:17:06.740 4855-4877/com.hashcube.sqmtest I/FlurryAgent: Agent report type: main device
07-02 15:17:06.745 4855-4877/com.hashcube.sqmtest D/FlurryAgent: Flushing deferred events queues.
07-02 15:17:06.745 4855-4855/com.hashcube.sqmtest D/SecWifiDisplayUtil: Metadata value : none
07-02 15:17:06.750 4855-4877/com.hashcube.sqmtest W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.hashcube.sqmtest/files/.YFlurrySenderIndex.info.AnalyticsMain

**Comment by CodeCombiner** [comment]
Fixed by replacing deprecated methods.
There is one error raised about that some method will be removed soon (not clear which) and Flurry will remove it from library. Was not able to remove it because it is no marked as deprecated and there is no point to look fo it now.
