### ISSUE TITLE
Gamecircle init error

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#23]
07-02 15:17:07.030 4855-4855/com.hashcube.sqmtest E/art: No implementation found for void com.amazon.ags.jni.AGSJniHandler.isLoaded() (tried Java_com_amazon_ags_jni_AGSJniHandler_isLoaded and Java_com_amazon_ags_jni_AGSJniHandler_isLoaded__)
07-02 15:17:07.030 4855-4855/com.hashcube.sqmtest I/AGSJniHandler: AmazonGamesJni is not loaded, trying to load library
07-02 15:17:07.040 4855-4855/com.hashcube.sqmtest W/AGSJniHandler: AmazonGamesJni not found.  Java Native Interface will not be available
07-02 15:17:07.040 4855-4855/com.hashcube.sqmtest D/com.amazon.identity.auth.device.utils.MAPLog.PII: Extracting verison incremental:<obscured>
    Incremental version '%s' was in invalid format.:<obscured>
07-02 15:17:07.045 4855-4855/com.hashcube.sqmtest D/com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.PII: AmazonAuthorizationManager:sdkVer=1.0.0 libVer=3.3.0:<obscured>
07-02 15:17:07.045 4855-4855/com.hashcube.sqmtest I/com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager: Options bundle is null
07-02 15:17:07.045 4855-4855/com.hashcube.sqmtest I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: getAppInfo : packageName=com.hashcube.sqmtest
    Finding API Key for com.hashcube.sqmtest
07-02 15:17:07.045 4855-4855/com.hashcube.sqmtest W/ResourcesManager: getTopLevelResources: /data/app/com.hashcube.sqmtest-1/base.apk / 1.0 running in com.hashcube.sqmtest rsrc of package null
07-02 15:17:07.215 4855-4855/com.hashcube.sqmtest I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Unable to get api key asset document: api_key.txt
07-02 15:17:07.215 4855-4855/com.hashcube.sqmtest W/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Unable to get API Key from Assests
07-02 15:17:07.215 4855-4855/com.hashcube.sqmtest I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Attempting to parse API Key from meta data in Android manifest
07-02 15:17:07.215 4855-4855/com.hashcube.sqmtest I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Begin decoding API Key for packageName=com.hashcube.sqmtest
07-02 15:17:07.215 4855-4855/com.hashcube.sqmtest D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: ApiKey/PackageName is null. pkg=com.hashcube.sqmtest:<obscured>
07-02 15:17:07.215 4855-4855/com.hashcube.sqmtest E/GameCircleClient: Unable to read api key.  GameCircle requires an api key to be included in 'assets/api_key.txt'.  GameCircle will not initialize.
    java.lang.IllegalArgumentException: Invalid API Key
        at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:126)
        at com.amazon.ags.api.AmazonGamesClient.initialize(AmazonGamesClient.java:131)
        at com.tealeaf.plugin.plugins.GameCirclePlugin.onResume(GameCirclePlugin.java:80)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tealeaf.plugin.PluginManager.invokeMethod(PluginManager.java:228)
        at com.tealeaf.plugin.PluginManager.callAll(PluginManager.java:263)
        at com.tealeaf.TeaLeaf.onRealResume(TeaLeaf.java:472)
        at com.tealeaf.TeaLeaf.onWindowFocusChanged(TeaLeaf.java:493)
        at com.android.internal.policy.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:3759)
        at android.view.View.dispatchWindowFocusChanged(View.java:10242)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1216)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4187)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by CodeCombiner** [comment]
After spending some time on investigation of the main issue `I/AGSJniHandler: AmazonGamesJni is not loaded, trying to load library` it seems that it should not be necessary to load this jni lib in case of using Java API. I think this issue can be bypassed if required. I will continue log analysis.
https://developer.amazon.com/docs/gamecircle/faq-gamecircle.html
<img width="899" alt="screen shot 2018-07-04 at 12 49 06 am" src="https://user-images.githubusercontent.com/2519305/42246287-bd8a8130-7f24-11e8-9c72-d5178ccf1382.png">

**Comment by CodeCombiner** [comment]
The todos still are:
1) Check if functions of  AmazonGamesJni.so are called.
2) `Unable to read api key.  GameCircle requires an api key to be included in 'assets/api_key.txt'.  GameCircle will not initialize.`
3) `com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding fails: certificate fingerprint can't be verified!`

**Comment by rampr** [comment]
I think the issue here is because of 2. We have to make sure the `api_key.txt` is being copied to the `assets/` folder

**Comment by rampr** [comment]
I just checked the build folder, api_key.txt isn't there. So it isn't getting copied and I think that is the issue

**Comment by CodeCombiner** [comment]
I think the problems is in sign keys. I will create new project and test with signed key. You can sign debug build with right key, not release build because it is not debuggable.

**Comment by CodeCombiner** [comment]
I registered new game in amazon developers console, gamecircle section. Used debug key data and package. Then used same package in android game and initialization was successful.
<img width="1338" alt="screen shot 2018-07-14 at 4 39 31 pm" src="https://user-images.githubusercontent.com/2519305/42724962-b5f4f78a-8784-11e8-8fd3-db2fb64f178e.png">

**Comment by rampr** [comment]
This is now fixed
