### ISSUE TITLE
Seemingly duplicate code in gradleops/AndroidSeed folder

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#25]
Looks like a lot of code is copied into gradleops.

Can the actual source files be used directly ?

**Comment by CodeCombiner** [comment]
This code was present for a short period of time. All duplication will be removed:
`native-adnroid/Tealeaf` - removed
`native-adnroid/native-core` - is a submodule which is copied everytime new game inited
`native-adnroid/GCTestApp` - I will delete this directory if you don't use it, please let me know

**Comment by rampr** [comment]
I didn't follow which directories are removed ?

I see both the `native-android/gradleops/AndroidSeed/tealeaf `and` native-android/tealeaf` still existing.

I was wondering if `native-android/gradleops/AndroidSeed/tealeaf` can be removed and `native-android/tealeaf` used directly

**Comment by rampr** [comment]
@CodeCombiner I saw the code that got removed.

I'm curious on why we can't retain `native-android/Tealeaf` and remove `native-android/gradleops/AndroidSeed/tealeaf`

I would prefer the dir structure to be retained as much as possible. Let me know your thoughts

**Comment by rampr** [comment]
Is this done @CodeCombiner  ?

**Comment by CodeCombiner** [comment]
Yes, I removed outdated ant project

**Comment by rampr** [comment]
Closing this :)
