### ISSUE TITLE
Change ouptupPath variable on start and remove "../.." throughout the project

### ISSUE THREAD

**Issue by CodeCombiner** [CodeCombiner/native-android#27]
Same for outputResources parameter

**Comment by CodeCombiner** [comment]
https://github.com/hashcube/native-android/pull/44#discussion_r206281995

**Comment by CodeCombiner** [comment]
@rampr , @vivekb91 current `opts.outputPath (build/native-android)` used debug/release scheme on path, i.e. `build/debug/native-android` or `build/release/native-android` this means that is will create 2 Android projects  (1 for debug and 1 for release). Please let me know if this is required and I should put this scheme.

Now it is made that /build/GAMENAME Android project dir is used for both schemes (.release and debug).

Let me know if `opts.outputPath` shell be either `build/GAMENAME` or `build/debug/GAMENAME`.
Please let me know your improvement ideas.

As well `opts.outputPath` can be `build/release/native-android/GAMENAME` which is too nested in my opinion or it can be  `build/release/native-android/` which will make Android game project bad transferable (I am not sure if you need to transfer Android Studio projects).

**Comment by rampr** [comment]
I would like build directory to be Android Studio compatible.
Please let me know what is generally done by other projects.

I will take a look at cocos2d and come back.

**Comment by CodeCombiner** [comment]
All build.gradle project are compatible with Android Studio. In Android Studio just select `import project`, do not select `open project` because Android Studio must import Gradle projects to generate Android Studio project files.

**Comment by rampr** [comment]
@CodeCombiner We prefer `build/release/native-android` and `build/debug/native-android`
`native-android` can be the project directory itself.

**Comment by CodeCombiner** [comment]
@rampr , I will apply such changes

**Comment by CodeCombiner** [comment]
Pull requests:
https://github.com/hashcube/freshchat/pull/17
https://github.com/hashcube/onesignal/pull/39
https://github.com/hashcube/firebase/pull/31
https://github.com/hashcube/gameplay/pull/19
https://github.com/hashcube/native-android/pull/50
https://github.com/hashcube/devkit-core/pull/74

Now the output path is like that: gamename/build/debug/native-android/gamename/

**Comment by rampr** [comment]
Will verify and close it Alex

**Comment by rampr** [comment]
zipalign seems to be failing 
![screen shot 2018-08-16 at 12 14 55 pm](https://user-images.githubusercontent.com/100719/44192709-1d8b7580-a14e-11e8-91e6-76beaaab93e6.png)

**Comment by rampr** [comment]
I have fixed it. I will push and then close this.

**Comment by rampr** [comment]
Fixed here -> https://github.com/hashcube/native-android/commit/39cb13ec785a5e07785defeddb8cf4153c0b1a52
