### ISSUE TITLE
Fix IronSource providers dependencies injection

### ISSUE THREAD

**Issue by CodeCombiner** [CodeCombiner/native-android#30]
Also remove unnecessary providers

**Comment by CodeCombiner** [comment]
Updated Facebook, Admob, Chartboost. It is desirable to test them.

**Comment by rampr** [comment]
Will check them and let you know if there are issues

**Comment by rampr** [comment]
Assigning it to us to test it out

**Comment by vivekb91** [comment]
chartboost is working

**Comment by vivekb91** [comment]
Rejecting re-init on previously-failed class java.lang.Class<com.ironsource.adapters.admob.AdMobAdapter$10>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/AdListener

This error is coming for admob

**Comment by rampr** [comment]
Admob is fixed here -> https://github.com/hashcube/ironsource/pull/11

**Comment by rampr** [comment]
Facebook ads and amazonads don't seem to be working. But closing it as it is low priority
