### ISSUE TITLE
App Name/Version Number and Code in App Info hardcoded to GameCircleSDK and 1.0

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#31]
![img_2466](https://user-images.githubusercontent.com/100719/42434040-3820fa16-836f-11e8-9ff1-e512a35f5db1.JPG)

**Comment by CodeCombiner** [comment]
Done Version Number and Code, App info

**Comment by rampr** [comment]
Yes, this seems to be done partly,
I was looking at the logs from #36 and looks like it has sqtest.

1. The only place sqtest is mentioned is in the manifest.json as bundleID under ios section. We just have to verify if it has been read from there

2. The Title has debug added to it. So the game on the device instead of SQ Test is called as SQ Test debug

**Comment by CodeCombiner** [comment]
Now I can see some settings in fastlane_conv.env
Do you use fastlane?

**Comment by rampr** [comment]
I was not using fastlane to build
Fastlane just creates the manifest.json in our case and runs devkit debug/release

**Comment by rampr** [comment]
The version number is not being taken from manifest.json

**Comment by CodeCombiner** [comment]
Fixed

**Comment by rampr** [comment]
Version number issue is fixed. Title still has debug appended to it

**Comment by rampr** [comment]
As dicussed, closing it
