### ISSUE TITLE
Build fails in NDK versions greater than r10

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#35]
Log:

```
xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
      [ndk-build]  clang++: error: unsupported option '-gstabs+'
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
           [xslt]  [error]  ERROR:  'Premature end of file.'
                   
                   [error]  ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
                   
        [android]  [error]  settings for AndroidManifest: value for package is not a string
                   [error]  settings for AndroidManifest: value for fullscreen is not a string
      [ndk-build]  make: *** [tealeaf/src/main/obj/local/armeabi-v7a/objs/tealeaf/js/js.o] Error 1
 [native-android]  android complete
          [build]  [error]  Error: ndk-build exited with non-zero exit code (2)
                   build failed
```

**Comment by CodeCombiner** [comment]
Please post how to reproduce. Shell not appear now.

**Comment by rampr** [comment]
It still happens. I just tried building it on ubuntu 17.04
Let me know if you need any details that you think would help

**Comment by CodeCombiner** [comment]
I want to reproduce this issue but I am not able. I might be wrong but it looks like you are using outdated native-android repo. 
1) Please clean cache, change repo and try again to be sure.
/home/USERNAME/.config/devkit/cache
2) Update NDK,
3) Ccheck if you have intalled with Android Studio, I am not sure but this might help:
1)) CMake
2)) LLDB
3)) NDK
![screenshot from 2018-07-16 22-32-43](https://user-images.githubusercontent.com/2519305/42779181-4b91bfca-8948-11e8-80ad-bfacbc7184fe.png)

4) Send please to me full console output.

I use Ubuntu 17.10 and never had this problems with updated repo.

**Comment by rampr** [comment]
I have done the changes and added steps 

1. Done
2. How to update ndk ?
3.  Android Studio screenshot
![android_studio](https://user-images.githubusercontent.com/100719/42816462-82b3db8c-89e8-11e8-9394-df2d6468ea8a.png) 
4. Log file attached - [linux.log](https://github.com/CodeCombiner/native-android/files/2201523/linux.log)

**Comment by CodeCombiner** [comment]
Your NDK version is the same. In front of NDK you can see "Installed", if update available you would see "Update available" like in front of "Android Emulator"

**Comment by rampr** [comment]
So it is updated then

**Comment by rampr** [comment]
This issue still happens on the Linux machine I am trying out

**Comment by CodeCombiner** [comment]
@rampr , please let me know the result of testing.

**Comment by rampr** [comment]
Still happens. I'm not sure if it is because clang isn't installed on that machine

**Comment by CodeCombiner** [comment]
What is output for `echo $NDK`?
Check please NDK version 
https://gist.github.com/jorgenpt/1961404

**Comment by rampr** [comment]
It is empty. Will try this gist and update here

**Comment by CodeCombiner** [comment]
Try to export like here but with your correct Android Ubuntu path
https://stackoverflow.com/a/29829234/2988832
Something like here
https://forum.hovatek.com/thread-1054.html

**Comment by rampr** [comment]
Vivek is checking it. He will report back with findings

**Comment by vivekb91** [comment]
We updated our source file,

export ANDROID_HOME=/home/hashcube-lenovo/Android/Sdk
export NDK_HOME=/home/hashcube-lenovo/Android/Sdk/ndk-bundle
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$NDK_HOME

but still issue is there

**Comment by vivekb91** [comment]
Error is still there, check the trace.

[error]  settings for AndroidManifest: value for app_links is not a string
                    [error]  settings for AndroidManifest: value for icons is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
        [jvmtools]  connected to localhost:32997
       [ndk-build]  Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in tealeaf/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
                    Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    
                    Android NDK: WARNING:tealeaf/src/main/jni/Android.mk:zip: LOCAL_LDLIBS is always ignored for static libraries    
         [android]  [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
       [ndk-build]  [armeabi-v7a] Compile++ thumb: tealeaf <= js.cpp
         [android]  [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
                    [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
                    [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
                    [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
                    [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
       [ndk-build]  clang++: error: unsupported option '-gstabs+'
         [android]  [error]  settings for AndroidManifest: value for package is not a string
                    [error]  settings for AndroidManifest: value for fullscreen is not a string
       [ndk-build]  make: *** [tealeaf/src/main/obj/local/armeabi-v7a/objs/tealeaf/js/js.o] Error 1
  [native-android]  android complete
           [build]  [error]  Error: ndk-build exited with non-zero exit code (2)
                    build failed

**Comment by CodeCombiner** [comment]
@rampr, you seems had this issue before, right? How did you come to fix it?
`[ndk-build] clang++: error: unsupported option '-gstabs+'`

**Comment by rampr** [comment]
Alex, I got it on the Linux machine. Vivek is also trying in the same machine.
We can maybe try in a different machine to see if we are getting the issue

**Comment by rampr** [comment]
The issue is because of NDK version. It only works with r9
