### ISSUE TITLE
Test Android strings localization

### ISSUE THREAD

**Issue by CodeCombiner** [CodeCombiner/native-android#39]

**Comment by rampr** [comment]
I'm not sure we need this. Let me know if you think we'll need this

**Comment by CodeCombiner** [comment]
It seems it is not required for now because all localized string are stored in plugins archives. Localization functionality is updated and shell be tested in future if it is required to add localized strings without adding them inside plugins archives.

**Comment by rampr** [comment]
I don't think it is needed. Closing this. We can reopen if needed
