### ISSUE TITLE
Enable 64 bit support

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#46]
Keep it optional so we can enable whenever we want

**Comment by CodeCombiner** [comment]
Set back and use TeaLeaf/generate.sh to generate profiles and other stuff for V8 to support 64 bit architecture.

**Comment by CodeCombiner** [comment]
Need to:
1) Update V8 to support new architecture
2) Generate profilers for 64 bit architecture
3) test and debug config and assembling during native building
