### ISSUE TITLE
execSync is undefined

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#53]
when building it is showing, execSync is undefined.
OS: ubuntu
tried installing npm module child_process, that also won't  have that function.

**Comment by CodeCombiner** [comment]
Try to update npm

**Comment by vivekb91** [comment]
we updated npm
➜  sudoku-quest-mobile git:(develop) npm -v
6.1.0
➜  sudoku-quest-mobile git:(develop) node -v
v10.7.0

It is not happening now
