### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#54]
Error loading module:
     [[ import resources.styles.landscape as style ]]
     requested by: /home/hashcube-lenovo/sudoku-quest-mobile/modules/devkithelper/src/style.js 
     current directory: /home/hashcube-lenovo/sudoku-quest-mobile 
   Error: Could not import `resources.styles.landscape`
  	looked in:
  		/home/hashcube-lenovo/sudoku-quest-mobile/resources/styles/landscape.js
  		/home/hashcube-lenovo/sudoku-quest-mobile/resources/styles/landscape/index.js
  	Import Stack:
  		
      at loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:699:17)
      at ENV_node.loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:473:18)
      at Function._require [as __require] (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:855:34)
      at run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:278:7)
      at exports (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:90:4)
      at applyPreprocessors (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:743:11)
      at loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:729:9)
      at ENV_node.loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:473:18)
      at Function._require [as __require] (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:855:34)
      at run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:278:7)
      at exports (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:90:4)
      at applyPreprocessors (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:743:11)
      at loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:729:9)
      at ENV_node.loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:473:18)
      at Function._require [as __require] (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:855:34)
      at run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:278:7)
      at exports (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:90:4)
      at applyPreprocessors (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:743:11)
      at loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:729:9)
      at ENV_node.loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:473:18)
      at Function._require [as __require] (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:855:34)
      at run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:278:7)
      at exports (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:90:4)
      at applyPreprocessors (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:743:11)
      at loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:729:9)
      at ENV_node.loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:473:18)
      at Function._require [as __require] (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:855:34)
      at run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:278:7)
      at exports (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:90:4)
      at applyPreprocessors (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:743:11)
      at loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:729:9)
      at ENV_node.loadModule (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:473:18)
      at _require (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:855:34)
      at /home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/jsio.js:88:27
      at Function.exports.compile (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/packages/preprocessors/compiler.js:274:2)
      at Object.exports.run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/compilers/jsio_compile/compiler.js:239:11)
      at run (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/src/build/jsCompiler.js:220:20)
      at Object.exports.start (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/jsio/compilers/jsio_compile/compiler.js:35:14)
      at /home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/src/build/jsCompiler.js:126:16
      at /home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/mkdirp/index.js:48:26
WARN jsio.preprocessors.compiler could not compile import from modules/devkithelper/src/style.js: import resources.styles.landscape as style
         [spriter]  not-cached b---resources-images-tutorial spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tutorial1.png
                    not-cached b---resources-images-tiles-map6 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-map61.png
                    not-cached b---resources-images-tiles-map5 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-map51.png
                    not-cached b---resources-images-tiles-map4 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-map41.png
                    not-cached b---resources-images-tiles-map3 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-map31.png
                    not-cached b---resources-images-tiles-map2 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-map21.png
                    not-cached b---resources-images-tiles-map1 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-map11.png
                    not-cached b---resources-images-tiles-comingsoon spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-comingsoon1.png
                    not-cached b---resources-images-tiles-bridge9 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge91.png
                    not-cached b---resources-images-tiles-bridge8 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge81.png
                    not-cached b---resources-images-tiles-bridge7 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge71.png
                    not-cached b---resources-images-tiles-bridge6 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge61.png
                    not-cached b---resources-images-tiles-bridge5 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge51.png
                    not-cached b---resources-images-tiles-bridge4 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge41.png
                    not-cached b---resources-images-tiles-bridge3 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge31.png
                    not-cached b---resources-images-tiles-bridge2 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge21.png
                    not-cached b---resources-images-tiles-bridge11 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge111.png
                    not-cached b---resources-images-tiles-bridge10 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge101.png
                    not-cached b---resources-images-tiles-bridge1 spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-tiles-bridge11.png
                    not-cached b---resources-images-story spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-story1.png
                    not-cached b---resources-images-puzzle_screen spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-puzzle_screen1.png
                    not-cached b---resources-images-popup-timeup spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-timeup1.png
                    not-cached b---resources-images-popup spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup1.png
                    not-cached b---resources-images-popup-store spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-store1.png
                    not-cached b---resources-images-popup-settings spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-settings1.png
                    not-cached b---resources-images-popup-sale spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-sale1.png
                    not-cached b---resources-images-popup-rating spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-rating1.png
                    not-cached b---resources-images-popup-promotion spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-promotion1.png
                    not-cached b---resources-images-popup-powerup spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-powerup1.png
                    not-cached b---resources-images-popup-play spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-play1.png
                    not-cached b---resources-images-popup-offer spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-offer1.png
                    not-cached b---resources-images-popup-gifting spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-gifting1.png
                    not-cached b---resources-images-popup-dailyspin spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-dailyspin1.png
                    not-cached b---resources-images-popup-dailypuzzle spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-dailypuzzle1.png
                    not-cached b---resources-images-popup-confirm spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-confirm1.png
                    not-cached b---resources-images-popup-common spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-common1.png
                    not-cached b---resources-images-popup-award spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-popup-award1.png
                    not-cached b---resources-images-menu_screen spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-menu_screen1.png
                    not-cached b---resources-images-map_screen spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-map_screen1.png
                    not-cached b---resources-images-loading_screen spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-loading_screen1.png
                    not-cached b---resources-images-common spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/resources-images-common1.png
                    not-cached b---modules-adventuremap-images-ui spritesheet missing: /home/hashcube-lenovo/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/assets/resources/spritesheets/modules-adventuremap-images-ui1.png
  [native-android]  spriter complete
                    sound-map complete
                    app-js complete
    [static-files]  creating manifest.json
  [native-android]  static-files complete
                    write-files complete
                    [error]  
⤷  process._tickCallback (internal/process/next_tick.js:98)
 ⤷  _combinedTickCallback (internal/process/next_tick.js:74)
  ⤷  endReadableNT (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_readable.js:1010)
   ⤷  Duplex.emit (events.js:185)
    ⤷  emitNone (events.js:91)
     ⤷  Duplex.g (events.js:286)
      ⤷  Duplex.onend (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_readable.js:577)
       ⤷  DestroyableTransform.Writable.end (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_writable.js:594)
        ⤷  endWritable (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_writable.js:638)
         ⤷  finishMaybe (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_writable.js:627)
          ⤷  prefinish (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_writable.js:619)
           ⤷  DestroyableTransform.emit (events.js:185)
            ⤷  emitNone (events.js:86)
             ⤷  DestroyableTransform.prefinish (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/readable-stream/lib/_stream_transform.js:138)
              ⤷  DestroyableTransform.onFinish [as _flush] (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/src/build/util/createFileStream.js:121)
               ⤷  Function.Promise.attempt.Promise.try (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/bluebird/js/main/method.js:31)
                ⤷  tryCatcher (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/bluebird/js/main/util.js:26)
                 ⤷  undefined (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/src/build/util/createFileStream.js:123)
                  ⤷  DestroyableTransform.androidBuild (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/src/build/targets/native/native-android.js:86)
                   ⤷  require (internal/module.js:20)
                    ⤷  Module.require (module.js:466)
                     ⤷  Function.Module._load (module.js:407)
                      ⤷  tryModuleLoad (module.js:415)
                       ⤷  Module.load (module.js:456)
                        ⤷  Object.Module._extensions..js (module.js:550)
                         ⤷  Module._compile (module.js:541)
                          ⤷  Object.<anonymous> (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/modules/native-android/build.js:20)
                           ⤷  Function.Promise.promisifyAll (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/bluebird/js/main/promisify.js:304)
                            ⤷  promisifyAll (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/bluebird/js/main/promisify.js:241)
                             ⤷  promisifiableMethods (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/bluebird/js/main/promisify.js:78)
                              ⤷  checkValid (/home/hashcube-lenovo/sudoku-quest-mobile/modules/devkit-core/node_modules/bluebird/js/main/promisify.js:55)
                               ⤷  undefined ()
                                ⤷  undefined (    See http://goo.gl/iWrZbw)
                                 ⤷  undefined ()
                                 TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
                    Unexpected error in stream android
                    android complete
           [build]  [error]  Error: error in android stream
                    build failed

**Comment by CodeCombiner** [comment]
Try please after #53 is fixed

**Comment by vivekb91** [comment]
@CodeCombiner we are checking in a different machine, #53 is not happening there. still do we need to update npm?

**Comment by CodeCombiner** [comment]
Please compare npm versions on that machines

**Comment by vivekb91** [comment]
just updated npm version now. installing modules again. it was 3.8 and 2.15.

**Comment by CodeCombiner** [comment]
Did that help?

**Comment by vivekb91** [comment]
Noe this error id not there,but #35 is blocking
