### ISSUE TITLE
devkit install not fetching submodules properly

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#55]
after running devkit install, devkit-core's submodule like native-ios and tilmestep has no files. in git status all the files showing as deleted.

**Comment by CodeCombiner** [comment]
I am checking this, it is releated to the works I am performing now. Android repo commit was unreachable and this interrupted submodules pulling.

**Comment by CodeCombiner** [comment]
It is fixed now. Should be working.

**Comment by rampr** [comment]
Assigning it to @vivekb91 to confirm
