### ISSUE TITLE
Application not running in browser simulator

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#56]
After changing all the modules application not working in browser simulator.

**Comment by CodeCombiner** [comment]
Please check again. It was related to installation interruption

**Comment by vivekb91** [comment]
will check and update

**Comment by vivekb91** [comment]
It is still happening, Please check the trace we got.

[apps]  /Users/vivek/hashcube_dev/sudoku-quest-mobile/manifest.json
          [devkit]  {ironsource} Adding provider chartboost
                    {ironsource} Adding provider facebook
                    {ironsource} Adding provider ironsource
           [build]  [error]  
⤷  processImmediate [as _immediateCallback] (timers.js:594)
 ⤷  tryOnImmediate (timers.js:622)
  ⤷  runCallback (timers.js:649)
   ⤷  Immediate.Async.drainQueues (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:15)
    ⤷  Async._drainQueues (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:133)
     ⤷  Async._drainQueue (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:128)
      ⤷  MappingPromiseArray.init (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/map.js:29)
       ⤷  MappingPromiseArray.init (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/promise_array.js:92)
        ⤷  MappingPromiseArray._promiseFulfilled (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/map.js:56)
         ⤷  tryCatcher (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/util.js:26)
          ⤷  undefined (/Users/vivek/.npm-packages/lib/node_modules/devkit/src/build/steps/buildHooks.js:74)
           ⤷  new Promise (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:71)
            ⤷  Promise._resolveFromResolver (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:483)
             ⤷  tryCatcher (/Users/vivek/.npm-packages/lib/node_modules/devkit/node_modules/bluebird/js/main/util.js:26)
              ⤷  Promise.then.data.module (/Users/vivek/.npm-packages/lib/node_modules/devkit/src/build/steps/buildHooks.js:75)
               ⤷  Object.exports.onBeforeBuild (/Users/vivek/hashcube_dev/sudoku-quest-mobile/modules/firebase/build/index.js:27)
                ⤷  Object.join (path.js:1211)
                 ⤷  assertPath (path.js:7)
                 TypeError: Path must be a string. Received undefined

**Comment by CodeCombiner** [comment]
Sudoku is not runinng really but Whack that mole runs well. I thin it is game compatibility.
It is related to  plist_file = 'GoogleService-Info.plist'. I suppose firebase plugin fails because this file is absent.
Please let me know if you have 'GoogleService-Info.plist' to test this game.

**Comment by rampr** [comment]
Alex, if the issue is that it doesn’t go past the first screen after tapping on play, timestep is not the latest

**Comment by rampr** [comment]
Updating timestep would fix it

**Comment by CodeCombiner** [comment]
I will try to update to latest because the commit used now is same as at hashcube repo https://github.com/hashcube/devkit-core/tree/hc/modules

**Comment by CodeCombiner** [comment]
Update to latest `gameclosure` did not help, the same error is present

**Comment by rampr** [comment]
Can you attach logs ? Also @CodeCombiner is the issue where you are able to tap on Play, but then the game gets stuck ?

**Comment by CodeCombiner** [comment]
Yes, the game stucks on loading screen. Please let me know if I should continue with it or if you know how to bypass it.
<img width="1417" alt="screen shot 2018-07-30 at 8 17 15 pm" src="https://user-images.githubusercontent.com/2519305/43412402-c6d4a4b6-9435-11e8-8d20-28bd1dd1774c.png">
<img width="1000" alt="screen shot 2018-07-30 at 8 19 41 pm" src="https://user-images.githubusercontent.com/2519305/43412448-f405d6da-9435-11e8-9c19-7511be62865e.png">

**Comment by CodeCombiner** [comment]
I am trying to understand this
<img width="976" alt="screen shot 2018-07-30 at 8 39 02 pm" src="https://user-images.githubusercontent.com/2519305/43413427-b5007802-9438-11e8-8a64-c4474ae4a725.png">

**Comment by rampr** [comment]
We have seen this issue go away when timestep  is the latest.

**Comment by CodeCombiner** [comment]
It has bypassed 1 step forward with latest Timestep but FB errors are still present. I am not sure but probably FB API has been changed, I suppose the result can be the same on real devices.
On next step the app get stuck with OPTIONS request error, I think it is related to CORS support.
<img width="953" alt="screen shot 2018-07-31 at 9 27 43 pm" src="https://user-images.githubusercontent.com/2519305/43479251-99a2a866-9508-11e8-9e73-bf283243286a.png">

**Comment by rampr** [comment]
the FB api error can be ignored on the simulator. This was because of how the facebook plugin was written.
If you are able to play the game, you can ignore it. Please confirm this.

**Comment by CodeCombiner** [comment]
I can not play game, I think that `OPTIONS` error on last screen does not allow to continue game loading. This might be not correct but I don't see any other errors.

**Comment by rampr** [comment]
OPTIONS error can be ignored. These are just network requests to our server and don't meddle with the working of the game.

Can you please switch to timestep in devkit-core(modules/devkit-core/modules/timestep) and let us know the last commit you see ?

**Comment by rampr** [comment]
![screen shot 2018-08-01 at 2 28 51 pm](https://user-images.githubusercontent.com/100719/43511903-43a1504a-9597-11e8-89e7-5541a9221245.png)
These should be in there.

**Comment by CodeCombiner** [comment]
I see the same
<img width="557" alt="screen shot 2018-08-01 at 6 52 09 pm" src="https://user-images.githubusercontent.com/2519305/43532820-114f0f5e-95bc-11e8-8a89-2947e32804d9.png">

**Comment by CodeCombiner** [comment]
I will try to re-init game from scratch

**Comment by rampr** [comment]
Let's do a video call/screen share to figure out the issue. We will also try re-init to verify.

**Comment by rampr** [comment]
This can be closed now I guess @CodeCombiner and @vivekb91.

Please reopen if we still have to look at it
