### ISSUE TITLE
Build failed 2

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#57]
tealeaf/src/main/jni/js/js_timestep_view.cpp:27:52: fatal error: gen/js_timestep_image_map_template.gen.h: No such file or directory
#include "gen/js_timestep_image_map_template.gen.h"

**Comment by CodeCombiner** [comment]
Done

**Comment by rampr** [comment]
I think this is also solved, closing it. We can reopen if it still exists
