### ISSUE TITLE
App crashing in android 8.0

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#58]
07-26 15:32:02.401 26860 26860 E AndroidRuntime: FATAL EXCEPTION: main
07-26 15:32:02.401 26860 26860 E AndroidRuntime: Process: com.hashcube.sqmtest, PID: 26860
07-26 15:32:02.401 26860 26860 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hashcube.sqmtest/com.hashcube.sqmtest.sqmtestActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.Activity.onCreate(Activity.java:995)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:321)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at com.tealeaf.TeaLeaf.onCreate(TeaLeaf.java:237)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at com.hashcube.sqmtest.sqmtestActivity.onCreate(sqmtestActivity.java:13)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6998)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
07-26 15:32:02.401 26860 26860 E AndroidRuntime: 	... 9 more
07-26 15:32:02.402 26860 26860 W System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hashcube.sqmtest/com.hashcube.sqmtest.sqmtestActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
07-26 15:32:02.402 26860 26860 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
07-26 15:32:02.402 26860 26860 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
07-26 15:32:02.402 26860 26860 W System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-26 15:32:02.402 26860 26860 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
07-26 15:32:02.402 26860 26860 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-26 15:32:02.402 26860 26860 W System.err: 	at android.os.Looper.loop(Looper.java:164)
07-26 15:32:02.402 26860 26860 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
07-26 15:32:02.402 26860 26860 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 15:32:02.402 26860 26860 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-26 15:32:02.402 26860 26860 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-26 15:32:02.402 26860 26860 W System.err: Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
07-26 15:32:02.402 26860 26860 W System.err: 	at android.app.Activity.onCreate(Activity.java:995)
07-26 15:32:02.403 26860 26860 W System.err: 	at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
07-26 15:32:02.403 26860 26860 W System.err: 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:321)
07-26 15:32:02.403 26860 26860 W System.err: 	at com.tealeaf.TeaLeaf.onCreate(TeaLeaf.java:237)
07-26 15:32:02.403 26860 26860 W System.err: 	at com.hashcube.sqmtest.sqmtestActivity.onCreate(sqmtestActivity.java:13)
07-26 15:32:02.403 26860 26860 W System.err: 	at android.app.Activity.performCreate(Activity.java:6998)
07-26 15:32:02.403 26860 26860 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
07-26 15:32:02.403 26860 26860 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
07-26 15:32:02.403 26860 26860 W System.err: 	... 9 more

**Comment by rampr** [comment]
Looks like this is a similar issue ->
https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o

**Comment by rampr** [comment]
@vivekb91 to confirm if it still exists

**Comment by vivekb91** [comment]
PR https://github.com/hashcube/native-android/pull/46/files
