### ISSUE TITLE
Ironsource issue while devkit debug and build failing

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#59]
**Unhandled rejection Error: ENOENT: no such file or directory, open '/home/panda/gradle/sudoku-quest-mobile/modules/ironsource/android/gradleclasspath.xml'
Unhandled rejection Error: ENOENT: no such file or directory, open '/home/panda/gradle/sudoku-quest-mobile/modules/ironsource/android/proguard.xml'**
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/CrashlyticsPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/AmazonAdPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/FlurryPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/GameCirclePlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/KochavaPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/PreferencesWrapper.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/OnesignalPlugin.java
                    Installing Java package com.android.vending.billing to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/FirebasePlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/FreshchatPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/GamePlayPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/IronSourcePlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/UtilsPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/BillingPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/LocalNotifyPlugin.java
                    Installing Java package com.tealeaf.plugin.plugins to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/tealeaf/src/main/java/com/tealeaf/plugin/plugins/FacebookPlugin.java
                    [warn]  No valid splash music specified in the manifest (at "splash.song")
                    Copying assets/api_key.txt to /home/panda/gradle/sudoku-quest-mobile/build/sqmtest/app/src/main/assets/api_key.txt
                    onesignalAppID1:  3645cb3e-9819-45a8-bf43-22d647f561c3
                    Copying resources/splash/portrait480.png to "assets/resources/splash-portrait480.png"
                    Copying resources/splash/portrait960.png to "assets/resources/splash-portrait960.png"
                    Copying resources/splash/portrait1024.png to "assets/resources/splash-portrait1024.png"
                    Copying resources/splash/portrait1136.png to "assets/resources/splash-portrait1136.png"
                    Copying resources/splash/portrait2048.png to "assets/resources/splash-portrait2048.png"
                    Copying resources/splash/portrait2960.png to "assets/resources/splash-portrait2960.png"
                    Copying resources/splash/landscape768.png to "assets/resources/splash-landscape768.png"
                    Copying resources/splash/landscape1536.png to "assets/resources/splash-landscape1536.png"
**Unhandled rejection Error: ENOENT: no such file or directory, open '/home/panda/gradle/sudoku-quest-mobile/modules/ironsource/android/gradleclasspath.xml'**

**Comment by CodeCombiner** [comment]
I have created new pull request. Please merge it and try again with removing /devkit/cache/ironsource and /mygame/modules/ironsource and with running devkit install

**Comment by rampr** [comment]
Don't see the PR @CodeCombiner

**Comment by rampr** [comment]
This has now been fixed with https://github.com/hashcube/ironsource/pull/9
