### ISSUE TITLE
Don't have to build for armeabi.  Only armeabi-v7a is sufficient

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#6]

**Comment by rampr** [comment]
This warning during build could be related to that too ->  

> Unable to strip library '/Users/rampr/work/hashcube/gradle/devkit/mygame/modules/devkit-core/modules/native-android/gradleops/mygame/tealeaf/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libtealeaf.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.

**Comment by CodeCombiner** [comment]
Seems to be fixed, no warnings appear
Please check the commit with tag "armeabi-v7a only" and reopen the issue if it is not ok.
