### ISSUE TITLE
Repositories not populating in the build.gradle.

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#60]
Plugin with id 'io.fabric' not found.came first. when we are checking the maven repos are not populated in the gradle file. it is happening in linux. we removed fabric and checked. that time the same error coming with com.google.gms.google-services.

**Comment by rampr** [comment]
This is related to #59 
Once this is resolved, this will get fixed

**Comment by rampr** [comment]
This is also solved
