### ISSUE TITLE
Test autoverify links in Android manifest

### ISSUE THREAD

**Issue by CodeCombiner** [CodeCombiner/native-android#62]
<img width="673" alt="screen shot 2018-07-30 at 10 44 17 am" src="https://user-images.githubusercontent.com/2519305/43384089-a0f914ca-93e5-11e8-8bbf-8ded5983a5b8.png">

**Comment by rampr** [comment]
Adding a reference to where we had used it
https://github.com/hashcube/native-android/commit/88d5d6b04f0f70c275482cb411a1f3d21231986f#diff-346839c0f3e1f08f1c7864d52e7df688

From what I remember, this was needed for launching our game from a http url for example

**Comment by CodeCombiner** [comment]
Pushed into PR#44

**Comment by rampr** [comment]
Thanks @CodeCombiner. We will verify it

**Comment by vivekb91** [comment]
it is working
