### ISSUE TITLE
util plugin manifest.xsl error

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#63]
INSTALL_STORE value have a unwanted space.

**Comment by CodeCombiner** [comment]
Do you mean this?
`<meta-data android:name="INSTALL_STORE" android:value="\ android"/>`
It seems that all of metadata includes `\ `
@rampr please confirm extra spaces are not required or were absent previously because they are applied to all variables during xsl transformation.

**Comment by vivekb91** [comment]
@CodeCombiner previously also the meta data was like this only.

<meta-data android:name="INSTALL_STORE" android:value="\ android"/>

but when we are calling meta.get("INSTALL_STORE").toString(). no white space was coming. but on the new version white is coming. I added logs at the same place for older version and the latest one. But this is the observation.

I am not sure why older version have that space.

@rampr

**Comment by rampr** [comment]
There used to be an issue where numbers were not considered as strings and hence we added space in the xsl(stylesheet file). Maybe it isn't needed anymore.

Example commit where it was first done.
https://github.com/gameclosure/facebook/commit/845c097e8d109fad5d415bfe5c69bb5c5fe5c566#diff-95a23de91ffc66f5664883c8296a32bf

**Comment by vivekb91** [comment]
> The issue is happening in some version of linux only. I will verify this. closing for now and once verified and needed i will reopen.

This is wrong observation. it is happening in mac also.

**Comment by CodeCombiner** [comment]
Removed whitespace
https://github.com/hashcube/utils/pull/18

**Comment by CodeCombiner** [comment]
Should I remove whitespaces in all plugins xsl or should we remove them only when errors found? Anyway we need to select the best approach of these two and continue fixing systematically.
@ram @vivekb91 , please let me know what module the bug is related to. I will check if it is fixed in module updates.

**Comment by CodeCombiner** [comment]
As well we can enhance pacth and just call everywhere `meta.get("INSTALL_STORE").toString().trim()`

**Comment by CodeCombiner** [comment]
This is not required any more and as it seems it is redundant because there are new methods added:
```
meta.get returns java Object
meta.getInt
meta.getDouble
meta.getString
```
We can remove empty spaces and backslashes during errors debugging or we can update all plugins at once. Please, open new issue if you want to do that.

**Comment by rampr** [comment]
We can create an issue and keep it low priority. I have no idea if it will break with the whitespace. We would have to test it out.

**Comment by vivekb91** [comment]
yes, we can create new one. It is here https://github.com/CodeCombiner/native-android/issues/71
