### ISSUE TITLE
Use syslink instead `cp -r native-core gradleops/AndroidSeed/tealeaf/src/main/jni/core`

### ISSUE THREAD

**Issue by CodeCombiner** [CodeCombiner/native-android#65]
After this completed
https://github.com/CodeCombiner/native-android/issues/51

**Comment by CodeCombiner** [comment]
Same pull requests for both tasks #65 and #51 as in last comment in the issue
https://github.com/CodeCombiner/native-android/issues/51

**Comment by rampr** [comment]
I think this is done. Closing.
