### ISSUE TITLE
App is crashing while connecting to google play

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#66]
This also look like due to the white space issue.

W/AudFlgTh(  277): Using by PID 21640, ProcessName:com.hashcube.sqmtest  
D/JS      (21640): 31 Jul 12:05:04 LOG console LOG gameplay {gameplay} Logging in a user
E/JS      (21640): {gameplay-native} value of connected_to  
E/JS      (21640): {gameplay-native} logged_in : true 
E/JS      (21640): {crashlytics inside logger 
E/JS      (21640): {plugins} WARNING: Unknown event could not be delivered for plugin: CrashlyticsPlugin , method: log 
W/FlurryAgent(21640): Event count started: settings_gamecircle
E/JS      (21640): {flurry} track - success: settings_gamecircle 
E/JS      (21640): {facebook} logEvent 
W/GamesServiceBroker( 1794): Client connected with SDK 12451000, Services 12874009, and Games 60840038
E/ValidateServiceOp( 1794): Application ID ( 979853579606) must be a numeric value. Please verify that your manifest refers to the correct project ID.
W/System.err(21640): java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
W/System.err(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source)
W/System.err(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source)
W/System.err(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source)
W/System.err(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
W/System.err(21640): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(21640): 	at android.os.Looper.loop(Looper.java:155)
W/System.err(21640): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
W/System.err(21640): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21640): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(21640): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
W/System.err(21640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
W/FlurryAgent(21640): Error logged: uncaught
E/AndroidRuntime(21640): FATAL EXCEPTION: main
E/AndroidRuntime(21640): Process: com.hashcube.sqmtest, PID: 21640
E/AndroidRuntime(21640): java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
E/AndroidRuntime(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source)
E/AndroidRuntime(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source)
E/AndroidRuntime(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source)
E/AndroidRuntime(21640): 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
E/AndroidRuntime(21640): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21640): 	at android.os.Looper.loop(Looper.java:155)
E/AndroidRuntime(21640): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/AndroidRuntime(21640): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21640): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21640): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
E/AndroidRuntime(21640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
W/ActivityManager(  681):   Force finishing activity com.hashcube.sqmtest/.sqmtestActivity
E/ActivityManager(  681): App crashed! Process: com.hashcube.sqmtest

**Comment by CodeCombiner** [comment]
How can I reproduce this?

**Comment by vivekb91** [comment]
1) open settings popup using button left button from map screen
2) there will be sign in button. just click on the button then app will crash.

If you are not able to see the sign in button, that will be because of the white space with the store INSTALLED_STORE value white space issue. remove that then sign in button will appear.

**Comment by rampr** [comment]
Vivek confirms this issue is happening. Assigning it to you @CodeCombiner

**Comment by rampr** [comment]
This is fixed.
