### ISSUE TITLE
Verify new onesignal change

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#69]
Test building and sending notifications.
https://github.com/hashcube/onesignal/pull/31

**Comment by vivekb91** [comment]
User not listing in the oensignal dashboard. I will debug and comment.

**Comment by vivekb91** [comment]
one signal app id is hardcoded in gradleapp.xml. It is not getting replaces properly.

**Comment by vivekb91** [comment]
Notifications are coming and user details are logging properly. Added new issues related to it and closing this.

Issues #74 , #73 

PR: https://github.com/hashcube/onesignal/pull/33/files
