### ISSUE TITLE
FB social activities are always asking for login

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#70]
Event after connection to Facebook, when trying to send invites or other FB activities it is asking user to connect to Facebook.

**Comment by CodeCombiner** [comment]
Need to test with signing keys that will make sudoku game to become accepted by Facebook application.

**Comment by CodeCombiner** [comment]
@vivekb91 how can I test sending invites or other FB activities?

**Comment by CodeCombiner** [comment]
For now it goes with `requests limit reached`
08-03 17:11:52.452 20088-20088/com.hashcube.sqmtest E/Profile: Got unexpected exception: {FacebookServiceException: httpResponseCode: 403, facebookErrorCode: 4, facebookErrorType: OAuthException, message: (#4) Application request limit reached}
https://developers.facebook.com/docs/graph-api/advanced/rate-limiting

I need to wait about 1 hour max and requests amount per time should be decreased.

**Comment by CodeCombiner** [comment]
Sometimes on Android 7.0 facebook responses after loggin in are stuck and app freezes.
Sometimes there is no reaction on response and connect/disconnect button not reacting to changes until open settings dialog again.
@vivekb91 the issue you describe appears when there is Facebook app installed on device. Everything works well and no issue appears if Facebook app not installed.

**Comment by rampr** [comment]
Thanks for these observations, we will also verify them.

**Comment by vivekb91** [comment]
@CodeCombiner yes you are correct. If there is no FB app it is working fine. I am testing in Android 8.0.0.

**Comment by CodeCombiner** [comment]
@vivekb91 I have found another case when try to sign in:
1)Go to settings
2)Press "Connect Now"
3) see "syncing your data now"
4) see "Oops! You were ...some text... could not be synced"
If you do this 1st time then dialog is not closed and Facebook button still shows "Connect Now" but should show "Disconnect" If you do this 2nd time then dialog is hidden and if settings panel is opened again then it is hidden well after data synching.

**Comment by rampr** [comment]
No. 4 is okay because it is our local server and that's why you get a message (Could not sync the data)
The message basically means facebook connection succeeded but syncing data from our server didn't succeed.

**Comment by vivekb91** [comment]
@CodeCombiner I will check the issue, I think this will be game side issue not related to new updates. I will check and update.

**Comment by vivekb91** [comment]
Dialog is closing for us, but the button text not chaining before closing. Once you done with #70 issue I will cross check again, it will most probably on our side only.

**Comment by CodeCombiner** [comment]
On Android 5.1.1. LG-g4s game stuck on splash with following test case:
1) Open game
2) Connect Facebook
3) Pass 5 levels after map is vesible
4) start next level
5) kill game
6) Open game
Result: game stucks with:
```
08-09 21:25:28.363 12727-12812/com.hashcube.sqmtest1 I/JS: http://com.hashcube.sqmtest1/modules/facebook/js/native/pluginImpl.js line: 125
          Object.defineProperties(this, {
    TypeError: Cannot redefine property: transform
        at Function.defineProperties (native)
        at Object.FBNativeInit [as init] (http://com.hashcube.sqmtest1/modules/facebook/js/native/pluginImpl.js:125:14)
        at Object.__bound [as init] (modules/devkit-core/node_modules/jsio/packages/base.js:90:41)
        at $$src_Module_facebook.Class.onGameLoad (http://com.hashcube.sqmtest1/src/Module/facebook.js:192:8)
        at Users_alex_codeworks_YG_reposAndroid_devkitworks_temp_devkit_sudoku_quest_mobile2_src_Application.<anonymous> (http://com.hashcube.sqmtest1/src/Application.js:130:24)
        at __bound (modules/devkit-core/node_modules/jsio/packages/base.js:90:41)
```

**Comment by CodeCombiner** [comment]
@vivekb91 
https://github.com/hashcube/facebook/pull/26
