### ISSUE TITLE
when building onesignal_app_id is changing in module also.

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#73]
we need to change the placeholders in build folder project only. But for onesignal values are changing module files also.

**Comment by vivekb91** [comment]
I will check for other modules also.

**Comment by vivekb91** [comment]
it is not happening for other modules. I think other modules wont have placeholders in gradleapp file.

**Comment by CodeCombiner** [comment]
We are going to link project instead of copying. In this case I think it will not work.
https://github.com/CodeCombiner/native-android/issues/51
Please let me know you ideas

**Comment by rampr** [comment]
I didn't understand the issue when we start linking the project instead of copying. Can you explain why please ?

**Comment by CodeCombiner** [comment]
I suppose we should start linking after  issue 51 completed
https://github.com/CodeCombiner/native-android/issues/51
If the issue 51 is completed, then this issue is irrelevant.

**Comment by vivekb91** [comment]
But the gradle.xsl files no need to change, right ?

**Comment by vivekb91** [comment]
@CodeCombiner currently we are changing the values on xsl file and copying that to main gradle file. We can change the placeholders while copying or after. we don't need to change the value in xsl file. for other plugins it working fine I guess, for onesignal only this issue happening.

**Comment by CodeCombiner** [comment]
I will make updates for this.

**Comment by CodeCombiner** [comment]
PRs
https://github.com/hashcube/native-android/pull/47
https://github.com/hashcube/onesignal/pull/35

**Comment by rampr** [comment]
@vivekb91 Please confirm and close

**Comment by vivekb91** [comment]
@rampr @CodeCombiner I will check
