### ISSUE TITLE
App generated inside build folder not working with android studio

### ISSUE THREAD

**Issue by vivekb91** [CodeCombiner/native-android#75]
When opening the project with android studio following errors are coming.

1. Gradle sync failed: Already disposed: Module: 'sqmtest-app' (11s 731ms)
2. The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

**Comment by CodeCombiner** [comment]
1. You should import project and use Android Studio 3.1.3 or 3.1.2 or 3.1.1 . Simple open project will not work
2. This warning does not impact on apk build process. This is side effect coming from one of plugins which is not updated recently.

**Comment by rampr** [comment]
@CodeCombiner  @vivekb91 Please confirm if this needs to be worked on then.

**Comment by vivekb91** [comment]
@rampr checking

**Comment by vivekb91** [comment]
it is working when importing.
