### ISSUE TITLE
Have freshchat to not use aar and only inject styles

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#76]
Current Freshchat approach I suggested is simple but might be not convenient to use.
I have another approach how to solve it.

The aar will be created
only variables will be injected in styles

2nd approach is easier to use but will require to rework existing approach.

We will use 2nd approach if possible. But this has to be done after everything else is complete.

**Comment by CodeCombiner** [comment]
Actually it will use aar because original  Freshchat gradle remote dependency require modifications. But 2nd approach will not require to rebuild aar everytime after aar is changed, it will change variables which then shell be injected in styles.xml

**Comment by rampr** [comment]
But will aar have to be created everytime freshchat makes a new release ?

**Comment by CodeCombiner** [comment]
If it is needed to update Freshchat SDK, then submodule should be updated, new aar generated and changes pushed into the repo.

**Comment by rampr** [comment]
Then I don't see much benefit. Please let me know your thoughts.

**Comment by CodeCombiner** [comment]
In current case it is required to rebuild Freshchat aar everytime a user changed style config and for everygame in a user wants to use different style for his game.
In 2nd approach it will require only to rebuild aar when Freshchat official SDK updated, once per 3 or 6 month about.

**Comment by rampr** [comment]
Understood Alex. It makes sense but is still low priority :) So until other things are done, let's not do this.
