### ISSUE TITLE
Verify if gradle builds of 2 projects can be installed on the same device

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#79]
We noticed an error when installing 2 different apps compiled using gradle

Vivek will verify the issue and add more details.

**Comment by vivekb91** [comment]
it is not working, showing INSTALL_FAILED_CONFLICTING_PROVIDER

**Comment by vivekb91** [comment]
We tried with whack-that-mole also. whack-that-mole able to install with sudoku. but whack-that-mole contains only devkit-core plugin.

when we are trying with mahjong it is not working.

**Comment by CodeCombiner** [comment]
The issue is solved but new updated Freshchat does not require any settings in maifest.xml
https://github.com/freshdesk/freshchat-android
Let me know if we should start to clean and test Manifest.xml injections.
Same PR as for issue #27 
https://github.com/hashcube/freshchat/pull/17

**Comment by rampr** [comment]
Will create a new issue for the same.
This issue is now fixed
