### ISSUE TITLE
Error in template file

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#9]
2 errors - sdkmanager not found
another is changing directory

```
[bash]  bash ./template sqmtest AndroidSeed com.hashcube.sqmtest
 ./template: line 3: sdkmanager: command not found
 ./template: line 5: cd: /modules/devkit-core/modules/native-android/gradleops/: No such file or directory
```

**Comment by CodeCombiner** [comment]
Solved:
1. `/template: line 5:` the line is removed and because it is not required
2. `./template: line 3: sdkmanager: command not found` error is related to environment setup and error description has been added to native-android README
