### ISSUE TITLE
Continuous logs on vendor.debug.egl.swapinterval

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#97]
04-29 12:03:09.311 27480 27553 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-29 12:03:09.509 27480 27553 I chatty  : uid=10330(com.hashcube.sqmtest) GLThread 12677 identical 12 lines
04-29 12:03:09.527 27480 27553 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-29 12:03:09.549 27480 27553 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-29 12:03:10.227 27480 27553 I chatty  : uid=10330(com.hashcube.sqmtest) GLThread 12677 identical 41 lines
04-29 12:03:10.250 27480 27553 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-29 12:03:10.249 27480 27480 W com.hashcube.sqmtest: type=1400 audit(0.0:785377): avc: denied { read } for comm=474C546872656164203132363737 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=22618 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
04-29 12:03:10.263 27480 27553 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
04-29 12:03:10.282 27480 27553 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"

**Comment by CodeCombiner** [comment]
I think this error is not critical according to this answer
https://stackoverflow.com/a/53916264
